"""add language to posts

Revision ID: 387b3f27c912
Revises: b5f683563aa9
Create Date: 2018-08-06 13:06:58.068610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387b3f27c912'
down_revision = 'b5f683563aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
